### ISSUE TITLE
Annotate PDF Advanced plugin produces error when creating an assignment

### ISSUE THREAD

**Issue by nsgreen749** [Kury25/moodle-assignfeedback_editpdfplus#23] opened 2021-08-26 14:21 UTC
Hi. I'm getting an error message on assignments when the Annotate PDF Advanced plugin is enabled. 
It throws an "exception - argument 1 passed to assign::calculate_properties() must be an instance of stdclass, null given, called in [dirroot]/mod/assign/locallib.php on line 1705" error. 
I'm using Moodle 3.10 (Build 20201211). 
I need this particular plugin to work, so disabling it doesn't solve my problem.

**Comment by ndunand** [comment] 2021-08-26 14:41
Tanks @nsgreen749 for chiming in on this and confirming this is still an issue. This is actually a duplicate of #19 .

I'm closing this and will follow in #19 .

**Closed as completed by ndunand** 2021-08-26 14:41 UTC
