### ISSUE TITLE
Request: Option for comments to be visible inline with work in downloadable PDF please

### ISSUE THREAD

**Issue by sgparry** [Kury25/moodle-assignfeedback_editpdfplus#15] opened 2019-03-17 09:46 UTC
Currently comments appear as footnotes at the bottom of the downloadable PDF. Where space is limited that is good, but often it is better to see the comment alongside / near the actual work, like the stamps. Can we please have an option on the tool to view the comment inline?

**Comment by Kury25** [comment] 2019-03-18 08:44
Hello, thanks for your feedback.

Are you talking about annotations written next to symbols? What is your idea exactly? to be able to indicate during the annotation the fact of appearing it online in the PDF file? or a global option?

The problem is size, and overlay, which is quite difficult to detect.
For now, what you see on the screen in the edition is not the "exact copy" of what you see in the PDF file. So even if the teacher sets the position of the annotations so that there is no overlap, the generated PDF could be unreadable.

**Comment by sgparry** [comment] 2019-03-18 13:34
What I want to be able to do is put my brief feedback comments (a sentence or two) in boxes that appear on screen and printout next to the relevant part of the students work, e.g. in the margin or the opposite page.
Another even better way this could be done is by either a)
Having marking pages you can insert opposite the student work that would contain the text of the feedback for that page, instead of at the end of the document as now or b)
Place a frame around the students work with a large righthand margin area in which the comments appear.
In both cases the pages or the frame could be blank or selected from a separate Mars heme document - allowing the student to see all three things (their work, your comments and the markscheme answer) in the same place on screen and printout. 

On 18 March 2019 08:44:12 GMT+00:00, Kury25 <notifications@github.com> wrote:
>Hello, thanks for your feedback.
>
>Are you talking about annotations written next to symbols? What is your
>idea exactly? to be able to indicate during the annotation the fact of
>appearing it online in the PDF file? or a global option?
>
>The problem is size, and overlay, which is quite difficult to detect.
>For now, what you see on the screen in the edition is not the "exact
>copy" of what you see in the PDF file. So even if the teacher sets the
>position of the annotations so that there is no overlap, the generated
>PDF could be unreadable.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Kury25/moodle-assignfeedback_editpdfplus/issues/15#issuecomment-473818849

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Kury25** [comment] 2019-03-19 10:31
ok, thanks for your interesting proposal, I will think about it.

**Comment by sgparry** [comment] 2019-05-10 08:28
Scaling back a bit, a fairly simple option that would be a really good start would be based on what was in Moodle prior to MDL-55459 (assignfeedback_editpdf: Add linked comments and markers to PDF). Looking at the code, it does not seem too hard to make the change they introduced optional, allowing you to toggle a comment between 'inline' and 'footnote' - I have filed a bug request, but i would make sense for you editpdfplus to have the same feature.

**Comment by Kury25** [comment] 2019-05-10 10:23
Yes we could simply add an option on the annotations for the pdf rendering. It is true. I'm going to code it for the next version.

**Comment by sgparry** [comment] 2019-05-10 11:25
Thank you, it will be a significant help to my marking.

On 10 May 2019 11:23:42 BST, Kury25 <notifications@github.com> wrote:
>Yes we could simply add an option on the annotations for the pdf
>rendering. It is true. I'm going to code it for the next version.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Kury25/moodle-assignfeedback_editpdfplus/issues/15#issuecomment-491240348

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Kury25** [comment] 2019-05-31 17:03
resolved in d84bac8c586b3867dfb40c986da894c22898922f

**Closed** 2019-05-31 17:03 UTC
